import { existsSync, readFileSync } from 'node:fs';
import { parse, stringify } from 'yaml';
import { writeFileAtomic } from '../lib/atomic-file.js';
import type { LockDeps } from '../lib/lock-file.js';
import { BASES_MEANINGFUL_FILTER } from '../receipts/policy.js';
import { INTERNALS, VAULT } from './layout.js';
import { requireVaultFolder, vaultFile } from './scope.js';
import { withVaultLock } from './vault-lock.js';

/** Exact leading ownership marker; arbitrary user Bases remain the person's. */
const OWNER = '# Generated by Mesa: Bases views\n';
export type BasesWritten = { written: string[]; kept: string[] };

const receiptColumns = [
  'file.name',
  'note.started',
  'note.kind',
  'note.project',
  'note.session',
  'note.status',
  'formula.target',
];
const receiptSort = [{ property: 'note.started', direction: 'DESC' }];
const sessionColumns = ['file.name', 'note.type', 'note.project', 'note.session', 'note.updated'];
const sessionSort = [{ property: 'note.updated', direction: 'DESC' }];
// A Base cannot canonicalise symlinks. Its links use the lexical scope rule and internal names.
const forbiddenTarget = ['\\.\\.', ...INTERNALS.map((name) => name.replaceAll('.', '\\.'))].join(
  '|',
);
const targetFormula = `if(outputs && outputs.target.isType("string") && outputs.target != "" && !outputs.target.startsWith("/") && !/(^|\\/)(${forbiddenTarget})(\\/|$)/i.matches(outputs.target), link(outputs.target), file.asLink())`;

// Global scope leaves historical receipts reachable; only default views apply meaningfulness.
const BASES = [
  {
    path: VAULT.receiptsBase,
    definition: {
      filters: { and: ['file.ext == "md"', `file.inFolder("${VAULT.receipts}")`] },
      formulas: {
        target: targetFormula,
      },
      views: [
        {
          type: 'table',
          name: 'Meaningful',
          filters: BASES_MEANINGFUL_FILTER,
          order: receiptColumns,
          sort: receiptSort,
        },
        {
          type: 'cards',
          name: 'By kind',
          filters: BASES_MEANINGFUL_FILTER,
          order: receiptColumns,
          sort: receiptSort,
          groupBy: { property: 'note.kind', direction: 'ASC' },
        },
        { type: 'table', name: 'Legacy (all receipts)', order: receiptColumns, sort: receiptSort },
      ],
    },
  },
  {
    path: VAULT.sessionsBase,
    definition: {
      filters: {
        and: [
          'file.ext == "md"',
          `!file.inFolder("${VAULT.receipts}")`,
          { or: ['type == "session-summary"', 'type == "decision"'] },
        ],
      },
      views: [
        { type: 'table', name: 'Sessions and decisions', order: sessionColumns, sort: sessionSort },
        {
          type: 'cards',
          name: 'By project',
          order: sessionColumns,
          sort: sessionSort,
          groupBy: { property: 'note.project', direction: 'ASC' },
        },
      ],
    },
  },
];

/** Write only owned fixed Bases, atomically under one vault lock; no history for derived views. */
export async function writeBases(
  deps: LockDeps & { vault: string; sleep: (ms: number) => Promise<void> },
): Promise<BasesWritten> {
  requireVaultFolder(deps.vault);
  return withVaultLock(deps, async () => {
    // Validate both destinations and read ownership before writing either one.
    const files = BASES.map(({ path, definition }) => {
      const file = vaultFile(deps.vault, path);
      const current = existsSync(file) ? readFileSync(file, 'utf8') : undefined;
      return {
        path,
        file,
        current,
        text: OWNER + stringify(definition, { aliasDuplicateObjects: false }),
      };
    });
    const result: BasesWritten = { written: [], kept: [] };
    for (const { path, file, current, text } of files) {
      if ((current !== undefined && !current.startsWith(OWNER)) || current === text) {
        result.kept.push(path);
      } else {
        writeFileAtomic(file, text);
        result.written.push(path);
      }
    }
    return result;
  });
}

/** Read-only view names survive native YAML saves; write ownership stays comment-based. */
export function baseViews(text: string): string[] | undefined {
  try {
    const base = parse(text) as { views?: unknown } | null;
    if (!Array.isArray(base?.views)) return undefined;
    const names = base.views.flatMap((view: { name?: unknown } | null) =>
      typeof view?.name === 'string' && view.name.trim() ? [view.name] : [],
    );
    return names.length === base.views.length ? names : undefined;
  } catch {
    return undefined;
  }
}
