import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  symlinkSync,
  utimesSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { runInNewContext } from 'node:vm';
import { beforeEach, expect, test } from 'vitest';
import { parse } from 'yaml';
import { createMesa } from '../mesa.js';
import { meaningfulReceipt, type RecordKind } from '../receipts/policy.js';
import type { Receipt } from '../receipts/schema.js';
import { projectProfile, scriptedRunner, tempDir, testDeps } from '../testing/index.js';
import { vaultLockPath } from './vault-lock.js';

let profile: ReturnType<typeof projectProfile>;
let vault: string;
beforeEach(() => {
  profile = projectProfile(scriptedRunner().run);
  vault = join(profile.home, 'vault');
});
const contents = (path: string) => readFileSync(join(vault, path), 'utf8');
const definition = (path: string) => parse(contents(path));

// Exercise generated expressions over invented data using only their documented JS-like subset.
// This is a policy/formula contract check, not an Obsidian renderer or native syntax proof.
const evaluate = (expression: string, row: Record<string, unknown>) =>
  runInNewContext(
    expression
      .replace(/([\w.]+)\.isType\("string"\)/g, '(typeof $1 === "string")')
      .replace(/([\w.]+)\.isType\("number"\)/g, '(typeof $1 === "number")')
      .replace(/([\w.]+)\.isType\("list"\)/g, 'Array.isArray($1)')
      .replace(
        /^if\((.*), link\(outputs.target\), file.asLink\(\)\)$/,
        '($1 ? link(outputs.target) : file.asLink())',
      )
      .replace(/\.matches\(/g, '.test('),
    {
      kind: null,
      status: null,
      outputs: null,
      ...row,
      link: (target: unknown) => target,
      file: { asLink: () => 'receipts/2026/09/example.md' },
    },
  );

test('public Bases write and read expose raw YAML, default views, columns, sorting and grouping', async () => {
  expect(await profile.mesa.vault.bases()).toEqual({
    written: ['receipts.base', 'sessions.base'],
    kept: [],
  });
  const receipts = definition('receipts.base');
  expect(contents('receipts.base')).toMatch(/^# Generated by Mesa: Bases views\nfilters:/);
  expect(receipts.filters).toEqual({ and: ['file.ext == "md"', 'file.inFolder("receipts")'] });
  expect(
    receipts.views.map((view: { name: string; type: string }) => [view.name, view.type]),
  ).toEqual([
    ['Meaningful', 'table'],
    ['By kind', 'cards'],
    ['Legacy (all receipts)', 'table'],
  ]);
  expect(receipts.views[0].order).toEqual([
    'file.name',
    'note.started',
    'note.kind',
    'note.project',
    'note.session',
    'note.status',
    'formula.target',
  ]);
  expect(receipts.views[0].sort).toEqual([{ property: 'note.started', direction: 'DESC' }]);
  expect(receipts.views[1].groupBy).toEqual({ property: 'note.kind', direction: 'ASC' });
  expect(receipts.views[1].filters).toBe(receipts.views[0].filters);
  expect(receipts.views[2]).not.toHaveProperty('filters');
  const sessions = definition('sessions.base');
  expect(sessions.filters).toEqual({
    and: [
      'file.ext == "md"',
      '!file.inFolder("receipts")',
      { or: ['type == "session-summary"', 'type == "decision"'] },
    ],
  });
  // A decision receipt has the same type as its note; the sessions view must exclude it.
  const inReceipts = sessions.filters.and[1];
  for (const [path, expected] of [
    ['wiki/decisions/tide.md', true],
    ['wiki/sessions/session-a.md', true],
    ['receipts/2026/09/decision-a.md', false],
  ] as const) {
    expect(
      runInNewContext(inReceipts, {
        file: { inFolder: (folder: string) => path.startsWith(`${folder}/`) },
      }),
    ).toBe(expected);
  }
  expect(
    sessions.views.map((view: { name: string; type: string }) => [view.name, view.type]),
  ).toEqual([
    ['Sessions and decisions', 'table'],
    ['By project', 'cards'],
  ]);
  expect(sessions.views[0].order).toEqual([
    'file.name',
    'note.type',
    'note.project',
    'note.session',
    'note.updated',
  ]);
  expect(sessions.views[0].sort).toEqual([{ property: 'note.updated', direction: 'DESC' }]);
  expect(sessions.views[1].groupBy).toEqual({ property: 'note.project', direction: 'ASC' });
  expect(profile.mesa.vault.read('receipts.base')).toMatchObject({
    preview: 'base',
    yaml: contents('receipts.base'),
    views: ['Meaningful', 'By kind', 'Legacy (all receipts)'],
  });
  expect(profile.mesa.vault.read('sessions.base')).toMatchObject({
    preview: 'base',
    views: ['Sessions and decisions', 'By project'],
  });
});

test('generated meaningful filter matches policy for decisions, changes, material guardrails and exclusions', async () => {
  await profile.mesa.vault.bases();
  const filter = definition('receipts.base').views[0].filters;
  const fixtures: [RecordKind | undefined, string, Record<string, unknown>, boolean][] = [
    ['decision', 'ok', {}, true],
    ['vault-change', 'ok', { target: 'wiki/tide.md' }, true],
    ['decision', 'failed', {}, false],
    ['vault-change', 'blocked', {}, false],
    ['connection', 'ok', { source: 'atlassian' }, true],
    ['connection', 'failed', {}, false],
    ['capture', 'ok', { notes: ['wiki/notes/tide.md'], target: 'wiki/notes/tide.md' }, true],
    ['capture', 'failed', { error: { code: 'internal' } }, false],
    ['refresh', 'ok', { refreshed: [] }, false],
    ['refresh', 'ok', { refreshed: ['LC-12'] }, true],
    ['refresh', 'ok', { refreshed: 'LC-12' }, false],
    ['refresh', 'ok', { refreshed: [], notesWritten: 1 }, true],
    ['refresh', 'ok', { refreshed: [], notesWritten: '1' }, false],
    ['refresh', 'failed', { refreshed: ['LC-12'] }, false],
    ['guardrail', 'ok', { override: 'accepted risk' }, true],
    ['guardrail', 'ok', {}, false],
    ['guardrail', 'ok', { override: true }, false],
    ['guardrail', 'ok', { dangerousFlags: '--dangerously-skip-permissions' }, true],
    ['guardrail', 'ok', { dangerousFlags: ['--sandbox'] }, false],
    [undefined, 'ok', { dangerousFlags: '--dangerously-skip-permissions' }, false],
    ['guardrail', 'ok', { sandboxOverride: 'read-only to workspace-write' }, true],
    ['guardrail', 'ok', { sandboxOverride: true }, false],
    ['guardrail', 'failed', { error: { code: 'guardrail_blocked' } }, true],
    ['guardrail', 'blocked', { error: { code: 'guardrail_blocked' } }, true],
    ['guardrail', 'failed', { error: { code: 'io_error' } }, false],
    [undefined, 'ok', {}, false],
    [undefined, 'failed', {}, false],
    ['vault-change', 'ok', { target: 'daily/2026-09-24.md' }, false],
    ['decision', 'ok', { target: 'daily' }, false],
    ['decision', 'ok', { target: 'daily-notes.md' }, true],
    ['decision', 'ok', { target: 12 }, true],
    ['decision', 'ok', { target: null }, true],
  ];
  for (const [kind, status, outputs, expected] of fixtures) {
    const policy = meaningfulReceipt({ kind, status, outputs } as Receipt);
    expect(policy).toBe(expected);
    expect(Boolean(evaluate(filter, { kind, status, outputs }))).toBe(expected);
  }
  expect(Boolean(evaluate(filter, { kind: 'routine', status: 'ok', outputs: {} }))).toBe(false);
  expect(Boolean(evaluate(filter, {}))).toBe(false);
});

test('target formula links exact scoped strings and falls back for absent, malformed or forbidden targets', async () => {
  await profile.mesa.vault.bases();
  const formula = definition('receipts.base').formulas.target;
  for (const target of ['wiki/tide.md', 'projects/lantern-cove.md', 'wiki/a b.md']) {
    expect(evaluate(formula, { outputs: { target } })).toBe(target);
  }
  for (const outputs of [
    undefined,
    {},
    { target: '' },
    { target: null },
    { target: 12 },
    { target: '/outside.md' },
    { target: '../outside.md' },
    { target: 'wiki/../../outside.md' },
    { target: 'wiki/.MeSa/secret.md' },
    { target: '.obsidian/app.json' },
  ]) {
    expect(evaluate(formula, { outputs })).toBe('receipts/2026/09/example.md');
  }
});

test('native-round-tripped Bases expose current views without adopting or rewriting user edits', async () => {
  await profile.mesa.vault.bases();
  const log = contents('log.md');
  const history = readdirSync(join(vault, 'receipts'), { recursive: true });
  const stamp = new Date('2020-01-01T00:00:00.000Z');
  for (const [path, names] of [
    ['receipts.base', ['Meaningful', 'By kind', 'Legacy (all receipts)']],
    ['sessions.base', ['Sessions and decisions', 'By project']],
  ] as const) {
    // Obsidian drops comments and canonicalises note properties on a native view save.
    const yaml = contents(path)
      .replace(/^# Generated by Mesa: Bases views\n/, '')
      .replaceAll('note.', '');
    writeFileSync(join(vault, path), yaml);
    utimesSync(join(vault, path), stamp, stamp);
    expect(profile.mesa.vault.read(path)).toMatchObject({
      preview: 'base',
      yaml,
      views: names,
      uri: `obsidian://open?vault=vault&file=${path}`,
    });
  }
  const edited = contents('receipts.base').replace(
    'name: Meaningful',
    'name: My meaningful history',
  );
  writeFileSync(join(vault, 'receipts.base'), edited);
  utimesSync(join(vault, 'receipts.base'), stamp, stamp);
  expect(profile.mesa.vault.read('receipts.base')).toMatchObject({
    yaml: edited,
    views: ['My meaningful history', 'By kind', 'Legacy (all receipts)'],
  });
  const before = ['receipts.base', 'sessions.base'].map((path) => readFileSync(join(vault, path)));
  expect(await profile.mesa.vault.bases()).toEqual({
    written: [],
    kept: ['receipts.base', 'sessions.base'],
  });
  for (const [index, path] of ['receipts.base', 'sessions.base'].entries()) {
    expect(readFileSync(join(vault, path))).toEqual(before[index]);
    expect(statSync(join(vault, path)).mtimeMs).toBe(stamp.getTime());
  }
  expect(contents('log.md')).toBe(log);
  expect(readdirSync(join(vault, 'receipts'), { recursive: true })).toEqual(history);
});

test('repeated writes preserve bytes, mtimes and history, and keep unmarked files', async () => {
  const log = contents('log.md');
  const history = readdirSync(join(vault, 'receipts'));
  await profile.mesa.vault.bases();
  const first = contents('receipts.base');
  const stamp = new Date('2020-01-01T00:00:00.000Z');
  utimesSync(join(vault, 'receipts.base'), stamp, stamp);
  const mtime = statSync(join(vault, 'receipts.base')).mtimeMs;
  expect(await profile.mesa.vault.bases()).toEqual({
    written: [],
    kept: ['receipts.base', 'sessions.base'],
  });
  expect(contents('receipts.base')).toBe(first);
  expect(statSync(join(vault, 'receipts.base')).mtimeMs).toBe(mtime);
  writeFileSync(join(vault, 'receipts.base'), 'views:\n  - name: Mine\n    type: table\n');
  writeFileSync(join(vault, 'sessions.base'), '# Generated by Mesa: Bases views\nviews: []\n');
  expect(await profile.mesa.vault.bases()).toEqual({
    written: ['sessions.base'],
    kept: ['receipts.base'],
  });
  expect(contents('receipts.base')).toBe('views:\n  - name: Mine\n    type: table\n');
  expect(profile.mesa.vault.read('receipts.base')).toHaveProperty('views', ['Mine']);
  writeFileSync(join(vault, 'receipts.base'), '# Generated by Mesa: Bases views\nviews: [broken\n');
  expect(profile.mesa.vault.read('receipts.base')).toMatchObject({
    preview: 'base',
    yaml: contents('receipts.base'),
  });
  expect(profile.mesa.vault.read('receipts.base')).not.toHaveProperty('views');
  expect(contents('log.md')).toBe(log);
  expect(readdirSync(join(vault, 'receipts'))).toEqual(history);
});

test('both fixed destinations are scoped before either write, including symlinks and folders', async () => {
  const outside = join(tempDir(), 'secret.base');
  writeFileSync(outside, 'Private invented content.\n');
  mkdirSync(join(vault, '.obsidian'), { recursive: true });
  writeFileSync(join(vault, '.obsidian/secret.base'), 'Internal.\n');
  for (const target of [
    outside,
    join(vault, '.obsidian/secret.base'),
    join(vault, 'missing.base'),
  ]) {
    symlinkSync(target, join(vault, 'sessions.base'));
    await expect(profile.mesa.vault.bases()).rejects.toMatchObject({ code: 'usage' });
    expect(existsSync(join(vault, 'receipts.base'))).toBe(false);
    rmSync(join(vault, 'sessions.base'));
  }
  mkdirSync(join(vault, 'sessions.base'));
  await expect(profile.mesa.vault.bases()).rejects.toThrow();
  expect(existsSync(join(vault, 'receipts.base'))).toBe(false);
  expect(readFileSync(outside, 'utf8')).toBe('Private invented content.\n');
});

test('missing vault is not created, and a held vault lock prevents writes', async () => {
  const lock = vaultLockPath(vault);
  mkdirSync(join(vault, '.mesa'), { recursive: true });
  writeFileSync(lock, 'other owner');
  // The controlled sleep seam avoids real retry delays while exercising the public service.
  const locked = createMesa('default', testDeps(profile.home, { sleep: async () => {} }));
  await expect(locked.vault.bases()).rejects.toMatchObject({ code: 'locked' });
  expect(contents('.mesa/lock')).toBe('other owner');
  expect(existsSync(join(vault, 'receipts.base'))).toBe(false);
  rmSync(vault, { recursive: true });
  await expect(profile.mesa.vault.bases()).rejects.toMatchObject({ code: 'not_found' });
  expect(existsSync(vault)).toBe(false);
});
