import {
  chmodSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  symlinkSync,
  utimesSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { multiProjectSession, newSession, shortIds, testStore } from '@mesa/core/testing';
import { beforeEach, expect, test } from 'vitest';
import { VERSION } from '../../cli.js';
import { cliHarness } from '../../testing.js';

const cli = cliHarness();
beforeEach(cli.reset);
const { mesa } = cli;

test('vault bases reports owned writes, keeps no-ops and user files, and reads view names', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  const vault = join(cli.home, 'vault');
  const log = readFileSync(join(vault, 'log.md'), 'utf8');
  expect((await mesa('vault', 'bases', '--json')).json.data).toEqual({
    written: ['receipts.base', 'sessions.base'],
    kept: [],
  });
  const receiptFile = join(vault, 'receipts.base');
  const before = readFileSync(receiptFile, 'utf8');
  const time = new Date('2020-01-01T00:00:00.000Z');
  utimesSync(receiptFile, time, time);
  expect((await mesa('vault', 'bases', '--json')).json.data).toEqual({
    written: [],
    kept: ['receipts.base', 'sessions.base'],
  });
  expect(readFileSync(receiptFile, 'utf8')).toBe(before);
  expect(statSync(receiptFile).mtimeMs).toBe(time.getTime());
  expect((await mesa('vault', 'read', 'receipts.base', '--json')).json.data.views).toEqual([
    'Meaningful',
    'By kind',
    'Legacy (all receipts)',
  ]);
  expect((await mesa('vault', 'read', 'receipts.base')).stdout).toContain('Meaningful');
  writeFileSync(receiptFile, before.replace(/^# Generated by Mesa: Bases views\n/, ''));
  expect((await mesa('vault', 'bases')).stdout).toContain('kept receipts.base');
  expect(readFileSync(receiptFile, 'utf8')).toBe(
    before.replace(/^# Generated by Mesa: Bases views\n/, ''),
  );
  expect((await mesa('vault', 'read', 'receipts.base', '--json')).json.data).toMatchObject({
    yaml: before.replace(/^# Generated by Mesa: Bases views\n/, ''),
    views: ['Meaningful', 'By kind', 'Legacy (all receipts)'],
    uri: 'obsidian://open?vault=vault&file=receipts.base',
  });
  expect(readFileSync(join(vault, 'log.md'), 'utf8')).toBe(log);
  expect((await mesa('receipts', '--json')).json.data).toEqual([]);
  const group = await mesa('vault');
  expect(group.stderr).toContain('vault bases');
});

test('vault bases refuses an escaping destination before writing the other file', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  writeFileSync(join(cli.home, 'outside.base'), 'Invented private file.\n');
  symlinkSync(join(cli.home, 'outside.base'), join(cli.home, 'vault/sessions.base'));
  const result = await mesa('vault', 'bases', '--json');
  expect(result.code).toBe(2);
  expect(result.json.error.message).toContain('outside the vault');
  expect(existsSync(join(cli.home, 'vault/receipts.base'))).toBe(false);
  expect(readFileSync(join(cli.home, 'outside.base'), 'utf8')).toBe('Invented private file.\n');
});

test('vault init lays out the vault once; vault status finds what is missing', async () => {
  // A new profile starts with its vault laid out; routine setup leaves no receipt.
  const made = await mesa('init', '--vault', 'vault', '--json');
  expect(made.json.data.vaultCreated).toEqual([
    'log.md',
    'AGENTS.md',
    'index.md',
    'raw',
    'wiki',
    'projects',
    'receipts',
    'daily',
  ]);
  expect((await mesa('vault', 'init')).stdout).toBe('vault already initialised\n');
  const log = readFileSync(join(cli.home, 'vault/log.md'), 'utf8').split('\n');
  expect(log[0]).toBe('- 2026-09-24T12:00:00.000Z vault initialised by mesa');
  expect(log[1]).toBe('');
  expect((await mesa('vault', 'init')).stdout).toBe('vault already initialised\n');
  expect((await mesa('vault', 'status', '--json')).json.data).toEqual({
    path: `${cli.home}/vault`,
    ok: true,
    missing: [],
  });

  rmSync(join(cli.home, 'vault/receipts'), { recursive: true });
  const status = await mesa('vault', 'status', '--json');
  expect(status.code).toBe(3);
  expect(status.json.data).toMatchObject({ ok: false, missing: ['receipts'] });

  const group = await mesa('vault');
  expect(group.code).toBe(2);
  expect(group.stderr).toContain('vault init');
  expect(group.stderr).toContain('vault status');
});

test('vault init refuses a non-empty folder that is not a vault unless --force', async () => {
  mkdirSync(join(cli.home, 'repo'));
  writeFileSync(join(cli.home, 'repo/README.md'), 'a repo\n');
  await mesa('init', '--vault', 'repo');
  expect((await mesa('vault', 'init')).code).toBe(4);
  expect((await mesa('vault', 'init', '--force')).code).toBe(0);
  expect(readFileSync(join(cli.home, 'repo/README.md'), 'utf8')).toBe('a repo\n');
});

test('log appends to log.md and to the daily note it creates', async () => {
  await mesa('init', '--vault', 'vault');
  const out = await mesa('log', 'hello', '--json');
  expect(out.code).toBe(0);
  expect(out.json.data.entry).toBe('- 2026-09-24T12:00:00.000Z hello <!-- mesa:log -->');
  expect(readFileSync(join(cli.home, 'vault/log.md'), 'utf8').trimEnd().split('\n').at(-1)).toBe(
    '- 2026-09-24T12:00:00.000Z hello <!-- mesa:log -->',
  );
  const daily = readFileSync(join(cli.home, 'vault', out.json.data.daily), 'utf8');
  expect(daily).toMatch(/^---\ncreated: /);
  expect(daily).toContain('- 2026-09-24T12:00:00.000Z hello\n<!-- mesa:daily:end -->');
  expect((await mesa('log')).code).toBe(2);
});

test('init, register, and vault init leave no routine receipt; receipts still validates queries', async () => {
  await mesa('init', '--vault', 'vault');
  mkdirSync(join(cli.home, 'tide'));
  await mesa('register', 'tide', '--create');
  await mesa('vault', 'init');
  await mesa('vault', 'init'); // nothing to do: no receipt

  const listed = await mesa('receipts', '--json', '--limit', '20');
  expect(listed.json.data).toEqual([]);
  expect((await mesa('receipts', 'show', '01NOPE')).code).toBe(3);
  expect(await mesa('receipts', '--limit', 'zero')).toMatchObject({
    code: 2,
    stderr: '--limit must be a whole number, not zero\n',
  });
  expect(await mesa('receipts', '--limit', '0')).toMatchObject({
    code: 2,
    stderr: 'the limit must be a positive whole number, not 0\n',
  });
  expect((await mesa('receipts', '--limit', '1', '--json')).json.data).toEqual([]);
});

test('a vault path that is not a vault omits routine receipts without warnings', async () => {
  mkdirSync(join(cli.home, 'repo/.git'), { recursive: true });
  writeFileSync(join(cli.home, 'repo/README.md'), 'a repo\n');
  const out = await mesa('init', '--vault', 'repo');
  expect(out.code).toBe(0);
  expect(out.stdout).not.toContain('warning:');
  expect(() => readFileSync(join(cli.home, 'repo/receipts'))).toThrow();
  const json = await mesa('--profile', 'json', 'init', '--vault', 'repo', '--json');
  expect(json.json.data).toMatchObject({
    receipt: null,
  });

  await mesa('--profile', 'work', 'init', '--vault', 'vault');
  mkdirSync(join(cli.home, 'nomesa'));
  expect((await mesa('--profile', 'work', 'register', 'nomesa')).code).toBe(3);
  const listed = await mesa('--profile', 'work', 'receipts', '--json');
  expect(listed.json.data).toEqual([]);
});

test('a routine action stays quiet when vault history cannot be written', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  mkdirSync(join(cli.home, 'tide'));
  chmodSync(join(cli.home, 'vault/log.md'), 0o000); // acceptsMesaWrites cannot read the log mark
  try {
    const ok = await mesa('register', 'tide', '--create');
    expect(ok.code).toBe(0);
    expect(ok.stdout).toContain('registered tide');
    expect(ok.stdout).not.toContain('warning:');
    const missing = await mesa('register', 'nowhere');
    expect(missing.code).toBe(3); // the real error, not the receipt's
  } finally {
    chmodSync(join(cli.home, 'vault/log.md'), 0o644);
  }
});

test('vault open: the URI by default, --json, and its errors', async () => {
  // No profile yet: the same error every command gives.
  const before = await mesa('vault', 'open');
  expect([before.code, before.stderr]).toEqual([
    3,
    `${cli.paths.config} not found; run mesa init --vault <path>\n`,
  ]);
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  // A config that does not read says why, as vault status does, not "no vault".
  const config = cli.paths.config;
  const good = readFileSync(config, 'utf8');
  writeFileSync(config, `${good}surprise: 1\n`);
  const broken = await mesa('vault', 'open');
  expect(broken.code).toBe(4);
  expect(broken.stderr).toMatch(/config\.yaml.*surprise/);
  writeFileSync(config, good);
  const list = join(cli.home, 'obsidian/obsidian.json');
  mkdirSync(join(cli.home, 'obsidian'), { recursive: true });
  writeFileSync(list, JSON.stringify({ vaults: { a1: { path: join(cli.home, 'vault'), ts: 1 } } }));

  const opened = await mesa('vault', 'open', '--json');
  expect(opened.json).toEqual({
    ok: true,
    data: { opened: true, method: 'uri', target: 'obsidian://open?vault=vault' },
  });
  const { daily } = (await mesa('log', 'hello', '--json')).json.data;
  const note = await mesa('vault', 'open', daily, '--json');
  expect(note.json.data.target).toBe(
    `obsidian://open?vault=vault&file=${encodeURIComponent(daily)}`,
  );
  expect((await mesa('vault', 'open', 'wiki/missing.md')).code).toBe(3);
});

test('vault list: every item as {vault, total, items}, filtered by --project and --type', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  const vault = join(cli.home, 'vault');
  const put = (path: string, text: string) => {
    mkdirSync(join(vault, path, '..'), { recursive: true });
    writeFileSync(join(vault, path), text);
  };
  put('projects/tide.md', '# Tide\n');
  put('wiki/currents.md', '---\nproject: tide\n---\nCurrents.\n');
  put('receipts/2026/09/20260924T120000Z-decision-01K62V4Q8J3M5N7P9R1S2T3V4W.md', 'Chose.\n');
  put('raw/chart.png', 'png');
  put('.obsidian/app.json', '{}');

  const listed = await mesa('vault', 'list', '--json');
  expect(listed.code).toBe(0);
  expect(listed.json.data).toMatchObject({ vault, total: 7 });
  expect(listed.json.data.items.map((i: { path: string }) => i.path)).toEqual([
    'AGENTS.md',
    'index.md',
    'log.md',
    'projects/tide.md',
    'raw/chart.png',
    'receipts/2026/09/20260924T120000Z-decision-01K62V4Q8J3M5N7P9R1S2T3V4W.md',
    'wiki/currents.md',
  ]);
  expect(listed.json.data.items[3]).toEqual({
    path: 'projects/tide.md',
    kind: 'markdown',
    category: 'projects',
    project: 'tide',
    size: 7,
    modified: expect.any(String),
  });

  const receipts = await mesa('vault', 'list', '--type', 'receipts', '--json');
  expect(receipts.json.data.total).toBe(1);
  const tide = await mesa('vault', 'list', '--project', 'tide', '--type', 'markdown', '--json');
  expect(tide.json.data.items.map((i: { path: string }) => i.path)).toEqual([
    'projects/tide.md',
    'wiki/currents.md',
  ]);
  expect((await mesa('vault', 'list', '--project', 'tide')).stdout).toBe(
    `markdown  projects  tide  projects/tide.md\nmarkdown  wiki      tide  wiki/currents.md\n2 items in ${vault}\n`,
  );
  expect(await mesa('vault', 'list', '--type', 'notes')).toMatchObject({ code: 2 });

  rmSync(vault, { recursive: true });
  const missing = await mesa('vault', 'list');
  expect([missing.code, missing.stderr]).toEqual([
    3,
    `vault ${vault} does not exist; run mesa vault init\n`,
  ]);
});

test('vault read: a note with its links and backlinks, a canvas, and an attachment, as JSON and text', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  const vault = join(cli.home, 'vault');
  const put = (path: string, text: string) => {
    mkdirSync(join(vault, path, '..'), { recursive: true });
    writeFileSync(join(vault, path), text);
  };
  put(
    'wiki/currents.md',
    '---\nproject: tide\n---\nSee [[tide]], ![[chart.png]] and [[eddies]].\n',
  );
  put('projects/tide.md', '# Tide\n\n[[currents]]\n');
  put('raw/chart.png', 'png');
  put('projects/tide/map.canvas', '{"nodes":[{"id":"a","type":"text","text":"Ebb"}],"edges":[]}');

  const note = await mesa('vault', 'read', 'wiki/currents.md', '--json');
  expect(note.code).toBe(0);
  expect(note.json.data).toMatchObject({
    path: 'wiki/currents.md',
    kind: 'markdown',
    project: 'tide',
    modified: expect.any(String),
    uri: 'obsidian://open?vault=vault&file=wiki%2Fcurrents.md',
    preview: 'markdown',
    frontmatter: { project: 'tide' },
    body: 'See [[tide]], ![[chart.png]] and [[eddies]].\n',
    backlinks: ['projects/tide.md'],
  });
  expect(note.json.data.links).toEqual([
    {
      text: '[[tide]]',
      start: 4,
      end: 12,
      syntax: 'wikilink',
      embed: false,
      target: 'tide',
      status: 'resolved',
      path: 'projects/tide.md',
    },
    expect.objectContaining({ embed: true, status: 'resolved', path: 'raw/chart.png' }),
    expect.objectContaining({ text: '[[eddies]]', status: 'broken' }),
  ]);
  expect((await mesa('vault', 'read', 'wiki/currents.md')).stdout).toBe(
    [
      'wiki/currents.md (markdown)',
      'project  tide',
      '',
      'See [[tide]], ![[chart.png]] and [[eddies]].',
      '',
      'links:',
      '  resolved  [[tide]]        projects/tide.md',
      '  resolved  ![[chart.png]]  raw/chart.png',
      '  broken    [[eddies]]',
      'backlinks:',
      '  projects/tide.md',
      'open: obsidian://open?vault=vault&file=wiki%2Fcurrents.md',
      '',
    ].join('\n'),
  );

  const canvas = await mesa('vault', 'read', 'projects/tide/map.canvas', '--json');
  expect(canvas.json.data).toMatchObject({ preview: 'canvas', nodes: 1, edges: 0, texts: ['Ebb'] });
  const png = await mesa('vault', 'read', 'raw/chart.png', '--json');
  expect(png.json.data).toMatchObject({
    kind: 'attachment',
    preview: 'unsupported',
    reason: 'Mesa does not preview images, audio, video, or PDFs',
    uri: 'obsidian://open?vault=vault&file=raw%2Fchart.png',
    backlinks: ['wiki/currents.md'],
  });
  expect((await mesa('vault', 'read', 'raw/chart.png')).stdout).toContain(
    'preview not available: Mesa does not preview images, audio, video, or PDFs\n',
  );

  expect(await mesa('vault', 'read', '.obsidian/app.json')).toMatchObject({
    code: 2,
    stderr: 'vault path .obsidian/app.json is a vault internal\n',
  });
  expect((await mesa('vault', 'read', 'wiki/missing.md')).code).toBe(3);
  expect((await mesa('vault', 'read')).code).toBe(2);
});

test('vault list and vault read agree on modified, and an edit on disk moves it', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  const file = join(cli.home, 'vault/wiki/currents.md');
  const edit = (text: string, at: string) => {
    writeFileSync(file, text);
    utimesSync(file, new Date(at), new Date(at));
  };
  const modified = async () => {
    const listed = (await mesa('vault', 'list', '--json')).json.data.items.find(
      (item: { path: string }) => item.path === 'wiki/currents.md',
    );
    const read = (await mesa('vault', 'read', 'wiki/currents.md', '--json')).json.data;
    return [listed.modified, read.modified, read.body];
  };
  edit('Ebb.\n', '2026-09-20T08:00:00.000Z');
  expect(await modified()).toEqual([
    '2026-09-20T08:00:00.000Z',
    '2026-09-20T08:00:00.000Z',
    'Ebb.\n',
  ]);
  edit('Flood.\n', '2026-09-20T08:00:05.000Z');
  expect(await modified()).toEqual([
    '2026-09-20T08:00:05.000Z',
    '2026-09-20T08:00:05.000Z',
    'Flood.\n',
  ]);
});

test('vault open opens the exact item, a canvas or a file with no extension', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  mkdirSync(join(cli.home, 'obsidian'), { recursive: true });
  writeFileSync(
    join(cli.home, 'obsidian/obsidian.json'),
    JSON.stringify({ vaults: { a1: { path: join(cli.home, 'vault'), ts: 1 } } }),
  );
  mkdirSync(join(cli.home, 'vault/raw/tide'), { recursive: true });
  writeFileSync(join(cli.home, 'vault/raw/tide/map.canvas'), '{}');
  writeFileSync(join(cli.home, 'vault/raw/tide/LICENSE'), 'invented');
  for (const path of ['raw/tide/map.canvas', 'raw/tide/LICENSE']) {
    const opened = await mesa('vault', 'open', path, '--json');
    expect(opened.json.data.target).toBe(
      `obsidian://open?vault=vault&file=${encodeURIComponent(path)}`,
    );
  }
});

test("vault save note --project names any of the session's projects, an additional one too", async () => {
  await cli.withProject();
  for (const name of ['tide-pool', 'driftwood']) {
    mkdirSync(join(cli.home, 'src', name));
    await mesa('register', '--create', join(cli.home, 'src', name));
  }
  const { id } = testStore(cli.home).create(() => multiProjectSession());
  const note = (project: string) =>
    mesa(
      'vault',
      'save',
      'note',
      '--project',
      project,
      '--session',
      id,
      '--title',
      'Client',
      '--text',
      'Invented.',
      '--json',
    );
  const saved = await note('tide-pool');
  expect(saved.code, saved.stdout).toBe(0);
  const text = readFileSync(join(cli.home, 'vault', saved.json.data.path), 'utf8');
  expect(text).toContain('project: tide-pool\n');
  expect(text).toContain(`session: "${id}"\n`);
  const elsewhere = await note('driftwood');
  expect(elsewhere.code).toBe(2);
  expect(elsewhere.json.error.message).toBe(
    `session ${id} is on lantern-cove, tide-pool, not driftwood`,
  );
});

test('vault save decision, summary, and note print {path, changed, receipt}; a repeat adds no receipt', async () => {
  cli.withTmux();
  await cli.withProject();
  const session = (await mesa('open', 'lantern-cove', '--json')).json.data.id;
  const count = async () => (await mesa('receipts', '--json', '--limit', '50')).json.data.length;
  writeFileSync(join(cli.home, 'summary.md'), 'Goal: fix the tide flake\nDone: fixed clock\n');
  const saves = [
    [
      'decision',
      '--project',
      'lantern-cove',
      '--title',
      'Fixed clock in tide tests',
      '--decision',
      'Tests take the clock as a parameter',
      '--rationale',
      'The flake was the wall clock at midnight',
      '--probability',
      'fixed-clock=0.8',
      '--probability',
      'retry=0.2',
      '--confidence',
      '0.8',
    ],
    ['summary', '--session', session, '--file', 'summary.md'],
    ['note', '--project', 'lantern-cove', '--title', 'Tide table sources', '--text', 'The office.'],
  ];
  const paths = [
    'wiki/decisions/2026-09-24-fixed-clock-in-tide-tests.md',
    `wiki/sessions/${session}.md`,
    'wiki/notes/tide-table-sources.md',
  ];
  for (const [i, save] of saves.entries()) {
    const before = await count();
    const first = await mesa('vault', 'save', ...save, '--json');
    expect(first.json.data).toEqual({
      path: paths[i],
      changed: true,
      receipt: { id: expect.any(String), path: expect.stringMatching(/^receipts\//) },
    });
    expect(await count()).toBe(before + 1);
    const again = await mesa('vault', 'save', ...save, '--json');
    expect(again.json.data).toEqual({ path: paths[i], changed: false, receipt: null });
    expect(await count()).toBe(before + 1);
  }
  const decision = readFileSync(join(cli.home, 'vault', paths[0] ?? ''), 'utf8');
  expect(decision).toContain('probabilities:\n  fixed-clock: 0.8\n  retry: 0.2\nconfidence: 0.8\n');
  const kinds = await mesa('receipts', '--project', 'lantern-cove', '--json');
  expect(kinds.json.data.map((e: { receipt: { kind: string } }) => e.receipt.kind)).toEqual([
    'vault-change',
    'vault-change',
    'decision',
  ]);
  // The receipt keeps a short command line, not the note's whole text.
  expect(
    (await mesa('vault', 'save', 'note', '--title', 'T', '--text', 'x'.repeat(300))).stdout,
  ).toBe('saved wiki/notes/t.md\n');
  const [latest] = (await mesa('receipts', '--limit', '1', '--json')).json.data;
  expect(latest.receipt.command.length).toBeLessThan(160);
});

test('vault save refuses bad flags, both text and file, other folders, and locked notes', async () => {
  await cli.withProject();
  const save = (...words: string[]) => mesa('vault', 'save', ...words);
  const decision = ['decision', '--project', 'lantern-cove', '--title', 't', '--decision', 'd'];
  expect((await save(...decision, '--rationale', 'r', '--probability', 'ship')).stderr).toBe(
    '--probability takes <option>=<p>, not ship\n',
  );
  expect((await save(...decision, '--rationale', 'r', '--probability', 'a=x')).code).toBe(2);
  expect(
    (await save(...decision, '--rationale', 'r', '--probability', 'a=1', '--probability', 'a=0'))
      .stderr,
  ).toBe('--probability names a twice\n');
  expect((await save(...decision, '--rationale', 'r', '--confidence', 'high')).code).toBe(2);
  expect((await save(...decision, '--rationale', 'r', '--confidence', '2')).code).toBe(2);
  expect((await save(...decision)).code).toBe(2); // --rationale is required
  writeFileSync(join(cli.home, 'note.md'), 'From a file.\n');
  expect((await save('note', '--title', 't', '--text', 'x', '--file', 'note.md')).code).toBe(2);
  expect((await save('note', '--title', 't')).code).toBe(2);
  expect((await save('note', '--title', 't', '--file', 'nope.md')).code).toBe(3);
  expect((await save('note', '--title', 't', '--text', 'x', '--path', 'raw/t.md')).stderr).toBe(
    'a note goes under wiki/ or projects/<project>/, not raw/t.md\n',
  );
  const vault = join(cli.home, 'vault');
  mkdirSync(join(vault, 'wiki/notes'), { recursive: true });
  writeFileSync(join(vault, 'wiki/notes/t.md'), '---\nsource: mesa\nlocked: true\n---\nMine\n');
  const locked = await save('note', '--title', 't', '--file', 'note.md', '--json');
  expect(locked.code).toBe(8);
  expect(locked.json.error).toMatchObject({ code: 'locked', details: { reason: 'note' } });
  expect((await mesa('receipts', '--json')).json.data).toEqual([]);
});

test('a title with a newline saved twice logs one line', async () => {
  await cli.withProject();
  const save = () =>
    mesa('vault', 'save', 'note', '--title', 'Tide\nTables', '--text', 'x', '--json');
  const saved = (await save()).json.data;
  expect(saved.path).toBe('wiki/notes/tide-tables.md');
  expect((await save()).json.data.changed).toBe(false);
  const log = readFileSync(join(cli.home, 'vault/log.md'), 'utf8');
  const link = saved.receipt.path.replace(/\.md$/, '');
  expect(log.split('\n').filter((line) => line.includes(link))).toEqual([
    `- 2026-09-24T12:00:00.000Z Saved note Tide Tables in wiki/notes/tide-tables [[${link}|receipt]]`,
  ]);
});

test('vault search: {total, truncated, items} with snippets, filtered by --project, --type, and --limit', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  const vault = join(cli.home, 'vault');
  const put = (path: string, text: string) => {
    mkdirSync(join(vault, path, '..'), { recursive: true });
    writeFileSync(join(vault, path), text);
  };
  put(
    'wiki/currents.md',
    '---\nproject: tide\n---\n# Currents\n\nThe foghorn sounds at the ebb.\n',
  );
  put('projects/tide/map.canvas', '{"nodes":[{"id":"a","type":"text","text":"Foghorn drill"}]}');
  put('raw/foghorn.png', 'png');
  put('.obsidian/foghorn.json', '{}');

  const found = await mesa('vault', 'search', 'FOGHORN', '--json');
  expect(found.code).toBe(0);
  expect(found.json.data.total).toBe(3);
  expect(found.json.data.truncated).toBe(false);
  expect(found.json.data.items[0]).toEqual({
    path: 'raw/foghorn.png',
    kind: 'attachment',
    title: 'foghorn.png',
    matches: [],
  });
  expect(found.json.data.items.map((i: { path: string }) => i.path).sort()).toEqual([
    'projects/tide/map.canvas',
    'raw/foghorn.png',
    'wiki/currents.md',
  ]);
  const tide = await mesa('vault', 'search', 'foghorn', '--project', 'tide', '--json');
  expect(tide.json.data.items.map((i: { path: string }) => i.path).sort()).toEqual([
    'projects/tide/map.canvas',
    'wiki/currents.md',
  ]);
  expect((await mesa('vault', 'search', 'foghorn', 'ebb', '--type', 'wiki')).stdout).toBe(
    'wiki/currents.md (markdown)\n  6: The foghorn sounds at the ebb.\n1 item\n',
  );
  const one = await mesa('vault', 'search', 'foghorn', '--limit', '1', '--json');
  expect([one.json.data.total, one.json.data.truncated, one.json.data.items.length]).toEqual([
    3,
    true,
    1,
  ]);
  expect((await mesa('vault', 'search', 'foghorn', '--limit', '1')).stdout).toMatch(
    /\n1 of 3 items\n$/,
  );
  expect((await mesa('vault', 'search', 'nothing-here')).stdout).toBe('0 items\n');
  expect(await mesa('vault', 'search', 'foghorn', '--limit', 'all')).toMatchObject({ code: 2 });
  expect(await mesa('vault', 'search', 'foghorn', '--type', 'notes')).toMatchObject({ code: 2 });
  expect(await mesa('vault', 'search')).toMatchObject({ code: 2 });
});

test('vault context and vault goals: a project overview and its earlier goals, as JSON and text', async () => {
  await mesa('init', '--vault', 'vault');
  await mesa('vault', 'init');
  mkdirSync(join(cli.home, 'tide'));
  await mesa('register', 'tide', '--create');
  const vault = join(cli.home, 'vault');
  const put = (path: string, text: string) => {
    mkdirSync(join(vault, path, '..'), { recursive: true });
    writeFileSync(join(vault, path), text);
  };

  // Nothing yet: empty lists and the hint.
  const empty = await mesa('vault', 'context', 'tide', '--json');
  expect(empty.json.data).toEqual({
    project: 'tide',
    hub: null,
    index: [],
    notes: [],
    decisions: [],
    goals: [],
    more: 'Nothing in the vault for tide yet: no hub at projects/tide.md, no notes, and no earlier sessions.',
  });

  put('projects/tide.md', '# Tide\n\n## Purpose\n\nTide tables.\n');
  put('wiki/currents.md', '---\nproject: tide\n---\n# Currents\n');
  put(
    'wiki/decisions/2026-09-20-fixed-clock.md',
    '---\nproject: tide\ntype: decision\n---\n# Fixed clock\n',
  );
  put('index.md', '# Index\n\n- [[wiki/currents]]: how the currents run\n');
  const store = testStore(cli.home, 'default', shortIds('aaaaaaaa', 'bbbbbbbb'));
  store.create(() =>
    newSession({
      project: 'tide',
      goal: 'Chart the neaps\nthen the springs',
      endedAt: '2026-09-24T13:00:00.000Z',
    }),
  );
  store.create(() => newSession({ project: 'tide', startedAt: '2026-09-25T12:00:00.000Z' }));
  put('wiki/sessions/aaaaaaaa.md', '# Summary\n');

  const context = await mesa('vault', 'context', 'tide', '--json');
  expect(context.code).toBe(0);
  expect(context.json.data).toMatchObject({
    project: 'tide',
    hub: { path: 'projects/tide.md', headings: ['# Tide', '## Purpose'] },
    index: ['- [[wiki/currents]]: how the currents run'],
    decisions: [
      {
        title: 'Fixed clock',
        path: 'wiki/decisions/2026-09-20-fixed-clock.md',
        when: '2026-09-20',
      },
    ],
    goals: [
      { id: 'bbbbbbbb', agent: 'claude' },
      { id: 'aaaaaaaa', summary: 'wiki/sessions/aaaaaaaa.md' },
    ],
  });
  // A summary names no project in its frontmatter here, so it is no note of tide's.
  expect(context.json.data.notes.map((n: { path: string }) => n.path)).toEqual([
    'wiki/currents.md',
  ]);
  const modified = context.json.data.notes[0].modified;
  expect((await mesa('vault', 'context', 'tide')).stdout).toBe(
    [
      'tide',
      'hub: projects/tide.md',
      '',
      '# Tide\n\n## Purpose\n\nTide tables.',
      '',
      'index:',
      '  - [[wiki/currents]]: how the currents run',
      'notes:',
      `  ${modified}  wiki/currents.md  Currents`,
      'decisions:',
      '  2026-09-20  wiki/decisions/2026-09-20-fixed-clock.md  Fixed clock',
      'goals:',
      '  bbbbbbbb  claude  2026-09-25T12:00:00.000Z  -',
      '  aaaaaaaa  claude  2026-09-24T12:00:00.000Z  Chart the neaps  wiki/sessions/aaaaaaaa.md',
      'Nothing left out. mesa vault read <path> reads a note in full, mesa vault list --project tide lists every item, and mesa vault goals tide lists earlier goals.',
      '',
    ].join('\n'),
  );

  const goals = await mesa('vault', 'goals', 'tide', '--limit', '1', '--json');
  expect(goals.json.data).toEqual([
    { id: 'bbbbbbbb', agent: 'claude', started: '2026-09-25T12:00:00.000Z' },
  ]);
  // Inside a session's window, that session is no earlier one.
  cli.env = { MESA_SESSION_ID: 'bbbbbbbb', MESA_PROFILE: 'default' };
  expect((await mesa('vault', 'goals', 'tide')).stdout).toBe(
    'aaaaaaaa  claude  2026-09-24T12:00:00.000Z  Chart the neaps  wiki/sessions/aaaaaaaa.md\n',
  );
  cli.env = {};

  const general = await mesa('vault', 'context', '--general', '--json');
  expect(general.json.data).toMatchObject({
    project: '__mesa_general__',
    hub: null,
    counts: { projects: 1, wiki: 3, index: 1 },
    goals: [],
  });
  expect((await mesa('vault', 'goals', '--general')).stdout).toBe('no earlier sessions\n');

  expect(await mesa('vault', 'context', 'nowhere')).toMatchObject({
    code: 3,
    stderr: 'no project named nowhere; see mesa projects\n',
  });
  for (const argv of [
    ['vault', 'context'],
    ['vault', 'goals', 'tide', '--general'],
  ]) {
    expect(await mesa(...argv)).toMatchObject({
      code: 2,
      stderr: 'pass a project or --general, not both\n',
    });
  }
  expect((await mesa('vault', 'goals', 'tide', '--limit', 'none')).code).toBe(2);
});

// The vault server (ADR-0011): `mesa vault mcp` over in-memory stdio, driven as an agent drives it.

/** A JSON-RPC request line; with no `id`, a notification's. */
const rpc = (id: number | undefined, method: string, params?: object) =>
  JSON.stringify({
    jsonrpc: '2.0',
    ...(id === undefined ? {} : { id }),
    method,
    ...(params ? { params } : {}),
  });
const call = (id: number, name: string, args: object = {}) =>
  rpc(id, 'tools/call', { name, arguments: args });
const initialize = (protocolVersion = '2025-11-25') =>
  rpc(1, 'initialize', {
    protocolVersion,
    capabilities: {},
    clientInfo: { name: 'a', version: '1' },
  });

type Reply = {
  jsonrpc: string;
  id: number | null;
  result?: { content: { text: string }[]; isError: boolean } & Record<string, unknown>;
  error?: { code: number; message: string };
};

/**
 * Runs `mesa [argv] vault mcp` on `input`, line by line; a function runs between the lines around
 * it. It prints nothing itself, and every line it writes is JSON-RPC 2.0: its replies, and stderr.
 */
async function serve(argv: string[], ...input: (string | (() => Promise<unknown>))[]) {
  const started = await mesa(...argv, 'vault', 'mcp');
  expect([started.code, started.stdout, started.stderr]).toEqual([0, '', '']);
  const stdout: string[] = [];
  const stderr: string[] = [];
  async function* lines() {
    for (const line of input) {
      if (typeof line === 'string') yield line;
      else await line();
    }
  }
  expect(started.serve).toBeTypeOf('function');
  await started.serve?.({
    lines: lines(),
    write: (text) => stdout.push(text),
    log: (text) => stderr.push(text),
  });
  const written = stdout.join('');
  expect(written.endsWith('\n') || written === '').toBe(true);
  const replies = written
    .split('\n')
    .filter(Boolean)
    .map((line) => JSON.parse(line) as Reply);
  for (const reply of replies) expect(reply.jsonrpc).toBe('2.0');
  return { replies, stderr: stderr.join('') };
}

/** A tool's answer: its text as JSON, which must not be an error. */
const answer = (reply: Reply | undefined) => {
  expect(reply?.result?.isError).toBe(false);
  return JSON.parse(reply?.result?.content[0]?.text ?? '');
};

/** A tool error's text. */
const refusal = (reply: Reply | undefined) => {
  expect(reply?.result?.isError).toBe(true);
  return reply?.result?.content[0]?.text;
};

/** An invented note in the vault. */
const put = (path: string, text: string) => {
  const file = join(cli.home, 'vault', path);
  mkdirSync(join(file, '..'), { recursive: true });
  writeFileSync(file, text);
};

/** Opens a session on lantern-cove, with `flags`; its id. */
async function openSession(...flags: string[]) {
  return (await mesa('open', 'lantern-cove', ...flags, '--json')).json.data.id as string;
}

/** A profile with lantern-cove, a tmux server whose windows end on /exit, and a session there. */
async function liveSession(...flags: string[]) {
  cli.withTmux({
    onKeys: (w, text) => {
      if (text === '/exit') w.dead = true;
    },
  });
  await cli.withProject();
  return openSession(...flags);
}

const TOOLS = [
  'project_context',
  'read_note',
  'search_vault',
  'session_goals',
  'save_decision',
  'save_summary',
  'save_note',
];

test('vault mcp serves a live session over stdio: initialize, tools/list, each tool, ping, and errors', async () => {
  const earlier = await liveSession('--goal', 'Chart the neaps');
  await mesa('stop', earlier);
  const id = await openSession();
  cli.env = { MESA_SESSION_ID: id, MESA_PROFILE: 'default' };
  put('projects/lantern-cove.md', '# Lantern cove\n\nThe harbour lights at dusk.\n');
  put('projects/lantern-cove/tides.md', 'The ebb turns at the harbour lights.\n');
  put('wiki/elsewhere.md', '---\nproject: tide\n---\nHarbour lights on another coast.\n');
  const listed = (await mesa('vault', 'mcp', '--tools', '--json')).json.data.tools;

  const { replies, stderr } = await serve(
    [],
    rpc(0, 'server/discover', { protocolVersion: '2026-07-28' }),
    initialize(),
    rpc(undefined, 'notifications/initialized'),
    rpc(2, 'tools/list'),
    call(3, 'project_context'),
    rpc(4, 'tools/call', {
      name: 'read_note',
      arguments: { path: 'projects/lantern-cove.md' },
      _meta: { progressToken: 4 },
    }),
    call(5, 'search_vault', { query: 'harbour lights' }),
    call(6, 'search_vault', { query: 'harbour lights', all: true }),
    call(7, 'session_goals'),
    call(8, 'save_decision', {
      title: 'Fixed clock in tide tests',
      decision: 'Tests take the clock as a parameter',
      rationale: 'The flake was the wall clock at midnight',
      probabilities: { 'fixed-clock': 0.8, retry: 0.2 },
      confidence: 0.8,
    }),
    call(9, 'save_summary', { summary: 'Goal: fix the tide flake\nDone: fixed clock\n' }),
    call(10, 'save_note', { title: 'Tide table sources', body: 'The harbour office.' }),
    rpc(11, 'ping'),
    call(12, 'no_such_tool'),
    rpc(13, 'resources/list'),
    'not json',
    rpc(undefined, 'notifications/roots/list_changed'),
  );
  expect(stderr).toBe(`mesa-vault: serving session ${id} (lantern-cove)\n`);
  // One reply per request, in order; none for a notification.
  expect(replies.map((r) => r.id)).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, null]);
  const [discover, init, list, context, read, search, all, goals, decision, summary, note, ping] =
    replies;
  // Antigravity asks server/discover first and falls back to initialize on -32601.
  expect(discover?.error).toEqual({ code: -32601, message: 'Method not found: server/discover' });
  expect(init?.result).toEqual({
    protocolVersion: '2025-11-25',
    capabilities: { tools: {} },
    serverInfo: { name: 'mesa-vault', version: VERSION },
  });
  expect(list?.result).toEqual({ tools: listed });
  expect(listed.map((t: { name: string }) => t.name)).toEqual(TOOLS);

  // Reads default to the session's project and leave the session itself out of its goals.
  expect(answer(context)).toMatchObject({
    project: 'lantern-cove',
    hub: { path: 'projects/lantern-cove.md', headings: ['# Lantern cove'] },
    notes: [{ path: 'projects/lantern-cove/tides.md' }],
    goals: [{ id: earlier, goal: 'Chart the neaps' }],
  });
  expect(answer(read)).toMatchObject({
    path: 'projects/lantern-cove.md',
    preview: 'markdown',
    body: '# Lantern cove\n\nThe harbour lights at dusk.\n',
  });
  // `all` searches the whole vault.
  const paths = (found: { items: { path: string }[] }) => found.items.map((i) => i.path).sort();
  expect(paths(answer(search))).toEqual([
    'projects/lantern-cove.md',
    'projects/lantern-cove/tides.md',
  ]);
  expect(paths(answer(all))).toEqual([
    'projects/lantern-cove.md',
    'projects/lantern-cove/tides.md',
    'wiki/elsewhere.md',
  ]);
  expect(answer(goals)).toEqual([
    {
      id: earlier,
      agent: 'claude',
      started: '2026-09-24T12:00:00.000Z',
      ended: '2026-09-24T12:00:00.000Z',
      goal: 'Chart the neaps',
    },
  ]);

  // Writes land for the session and its project, each with one receipt the session is actor of.
  const saved = [decision, summary, note].map(answer);
  expect(saved.map((s) => s.path)).toEqual([
    'wiki/decisions/2026-09-24-fixed-clock-in-tide-tests.md',
    `wiki/sessions/${id}.md`,
    'wiki/notes/tide-table-sources.md',
  ]);
  for (const s of saved) {
    expect(s).toMatchObject({ changed: true, receipt: { id: expect.any(String) } });
  }
  const frontmatter = async (path: string) =>
    (await mesa('vault', 'read', path, '--json')).json.data.frontmatter;
  expect(await frontmatter(saved[0].path)).toMatchObject({
    type: 'decision',
    project: 'lantern-cove',
    session: id,
    probabilities: { 'fixed-clock': 0.8, retry: 0.2 },
    confidence: 0.8,
  });
  expect(await frontmatter(saved[2].path)).toMatchObject({ project: 'lantern-cove', session: id });
  const receipts = (await mesa('receipts', '--session', id, '--json')).json.data;
  expect(receipts.map((e: { receipt: { actor: string } }) => e.receipt.actor)).toEqual([
    id,
    id,
    id,
  ]);

  expect(ping?.result).toEqual({});
  expect(replies[12]?.error).toEqual({ code: -32602, message: 'Unknown tool: no_such_tool' });
  expect(replies[13]?.error).toEqual({ code: -32601, message: 'Method not found: resources/list' });
  expect(replies[14]?.error).toEqual({ code: -32700, message: 'Parse error' });
});

test('vault mcp answers the protocol version a client asks for when it speaks it, else its newest', async () => {
  for (const [asked, given] of [
    ['2025-06-18', '2025-06-18'],
    ['2025-11-25', '2025-11-25'],
    ['2099-01-01', '2025-11-25'],
  ]) {
    const { replies } = await serve([], initialize(asked));
    expect(replies[0]?.result?.protocolVersion).toBe(given);
  }
});

test('vault mcp refuses invalid request envelopes before dispatching them', async () => {
  const invalid = [
    { jsonrpc: '1.0', id: 2, method: 'ping' },
    { id: 3, method: 'ping' },
    { jsonrpc: '2.0', id: {}, method: 'ping' },
    { jsonrpc: '2.0', id: false, method: 'ping' },
    { jsonrpc: '2.0', id: null, method: 'ping' },
    { jsonrpc: '2.0', id: [], method: 'tools/list' },
  ];
  const { replies } = await serve([], ...invalid.map((m) => JSON.stringify(m)), rpc(4, 'ping'));
  expect(replies.slice(0, -1)).toEqual(
    invalid.map(() => ({
      jsonrpc: '2.0',
      id: null,
      error: { code: -32600, message: 'Invalid request' },
    })),
  );
  expect(replies.at(-1)).toMatchObject({ id: 4, result: {} });
});

test('vault mcp stays inert with a corrupt session record and still initializes', async () => {
  const id = await liveSession();
  cli.env = { MESA_SESSION_ID: id, MESA_PROFILE: 'default' };
  const record = join(cli.home, '.mesa/default/sessions', `${id}.json`);
  writeFileSync(record, 'not json');
  const { replies, stderr } = await serve(
    [],
    initialize(),
    rpc(2, 'tools/list'),
    call(3, 'save_note', { title: 'Stray', body: 'Invented' }),
  );
  expect(replies[0]?.result?.protocolVersion).toBe('2025-11-25');
  expect(replies[1]?.result).toEqual({ tools: [] });
  expect(refusal(replies[2])).toContain('mesa-vault is inert:');
  expect(stderr).toContain('session binding failed:');
  expect(existsSync(join(cli.home, 'vault/wiki/notes/stray.md'))).toBe(false);
});

test('outside a live session of its profile, vault mcp lists no tools and refuses every call, reading and writing nothing', async () => {
  const live = await liveSession();
  const ended = await openSession();
  await mesa('stop', ended);
  const removed = await openSession();
  await mesa('stop', removed);
  await mesa('rm', removed);
  put('wiki/tide.md', 'The ebb at the harbour lights.\n');
  const cases: [string[], Record<string, string>, string][] = [
    [[], {}, 'MESA_SESSION_ID is not set: this is not a Mesa session'],
    [
      [],
      { MESA_SESSION_ID: 'zzzzzzzz', MESA_PROFILE: 'default' },
      'profile default has no session zzzzzzzz: it is unknown or was removed',
    ],
    [[], { MESA_SESSION_ID: ended }, `session ${ended} ended at 2026-09-24T12:00:00.000Z`],
    [
      [],
      { MESA_SESSION_ID: removed },
      `profile default has no session ${removed}: it is unknown or was removed`,
    ],
    // Another profile's session: the id is default's, the server work's.
    [
      ['--profile', 'work'],
      { MESA_SESSION_ID: live, MESA_PROFILE: 'work' },
      `profile work has no session ${live}: it is unknown or was removed`,
    ],
    [
      [],
      { MESA_SESSION_ID: live, MESA_PROFILE: 'work' },
      `session ${live} is profile work's, not default's`,
    ],
  ];
  for (const [argv, env, reason] of cases) {
    cli.env = env;
    const { replies, stderr } = await serve(
      argv,
      initialize(),
      rpc(undefined, 'notifications/initialized'),
      rpc(2, 'tools/list'),
      call(3, 'read_note', { path: 'wiki/tide.md' }),
      call(4, 'save_note', { title: 'Stray', body: 'Written from outside.' }),
      call(5, 'no_such_tool'),
    );
    expect(replies[0]?.result).toMatchObject({ protocolVersion: '2025-11-25' });
    expect(replies[1]?.result).toEqual({ tools: [] });
    for (const reply of replies.slice(2)) {
      expect(refusal(reply)).toBe(`mesa-vault is inert: ${reason}`);
    }
    expect(stderr).toBe(`mesa-vault: listing no tools: ${reason}\n`);
  }
  expect(existsSync(join(cli.home, 'vault/wiki/notes'))).toBe(false);
  cli.env = {};
  expect((await mesa('receipts', '--json')).json.data).toEqual([]);
});

test('a session stopped while its server runs is refused from its next request on', async () => {
  const id = await liveSession();
  cli.env = { MESA_SESSION_ID: id, MESA_PROFILE: 'default' };
  const { replies } = await serve(
    [],
    initialize('2025-06-18'),
    rpc(2, 'tools/list'),
    async () => {
      cli.env = {};
      await mesa('stop', id);
    },
    rpc(3, 'tools/list'),
    call(4, 'save_note', { title: 'Late', body: 'Saved after the stop.' }),
  );
  expect(replies[1]?.result?.tools).toHaveLength(TOOLS.length);
  expect(replies[2]?.result).toEqual({ tools: [] });
  expect(refusal(replies[3])).toBe(
    `mesa-vault is inert: session ${id} ended at 2026-09-24T12:00:00.000Z`,
  );
  expect(existsSync(join(cli.home, 'vault/wiki/notes/late.md'))).toBe(false);
});

test('a background session resumed under a new record is served through the binding its process kept', async () => {
  const ended = await liveSession();
  const base = cli.run;
  cli.run = (file, args, ms, options) =>
    file === 'claude' && ['--bg', 'stop'].includes(args[0] ?? '')
      ? Promise.resolve({ ok: true, stdout: 'backgrounded · abcdef12\n' })
      : base(file, args, ms, options);
  const first = await openSession('--background');
  await mesa('stop', first);
  const resumed = (await mesa('resume', first, '--json')).json.data.id as string;
  // Claude restarts the job for the attach with its launch's settings env: the first record's.
  cli.env = { MESA_SESSION_ID: first, MESA_PROFILE: 'default' };
  const { replies } = await serve(
    [],
    initialize(),
    rpc(2, 'tools/list'),
    call(3, 'save_summary', { summary: 'Goal: chart the neaps. Done: the tide table.' }),
    async () => {
      cli.env = {};
      await mesa('stop', resumed);
      cli.env = { MESA_SESSION_ID: first, MESA_PROFILE: 'default' };
    },
    rpc(4, 'tools/list'),
  );
  expect(replies[1]?.result?.tools).toHaveLength(TOOLS.length);
  expect(answer(replies[2])).toMatchObject({ path: `wiki/sessions/${resumed}.md`, changed: true });
  expect(replies[3]?.result).toEqual({ tools: [] });
  // A resumed foreground session is not followed: its process ended with its record.
  cli.env = {};
  await mesa('stop', ended);
  expect((await mesa('resume', ended)).code).toBe(0);
  cli.env = { MESA_SESSION_ID: ended, MESA_PROFILE: 'default' };
  const { stderr } = await serve([], initialize(), rpc(2, 'tools/list'));
  expect(stderr).toBe(
    `mesa-vault: listing no tools: session ${ended} ended at 2026-09-24T12:00:00.000Z\n`,
  );
});

test('a session record that stops reading makes the server inert and logs the binding failure', async () => {
  const id = await liveSession();
  cli.env = { MESA_SESSION_ID: id, MESA_PROFILE: 'default' };
  const record = join(cli.paths.sessions, `${id}.json`);
  const { replies, stderr } = await serve(
    [],
    initialize(),
    async () => writeFileSync(record, 'not json'),
    rpc(2, 'tools/list'),
    call(3, 'read_note', { path: 'index.md' }),
  );
  const why = `${record}: not valid JSON`;
  expect(replies[1]?.result).toEqual({ tools: [] });
  expect(refusal(replies[2])).toBe(`mesa-vault is inert: session binding failed: ${why}`);
  expect(stderr.split('\n').slice(1)).toEqual([
    `mesa-vault: session binding failed: ${why}`,
    `mesa-vault: session binding failed: ${why}`,
    '',
  ]);
});

test("the server's calls refuse canonical-path, symlink-escape, and internal paths, another project's folder, and bad arguments", async () => {
  const id = await liveSession();
  cli.env = { MESA_SESSION_ID: id, MESA_PROFILE: 'default' };
  const vault = join(cli.home, 'vault');
  const secret = join(cli.home, 'secret.md');
  writeFileSync(secret, 'Outside the vault.\n');
  mkdirSync(join(cli.home, 'elsewhere'));
  mkdirSync(join(vault, 'wiki'), { recursive: true });
  symlinkSync(secret, join(vault, 'wiki/escape.md'));
  symlinkSync(join(cli.home, 'elsewhere'), join(vault, 'wiki/out'));
  put('.obsidian/app.json', '{}');
  const { replies } = await serve(
    [],
    initialize(),
    call(2, 'read_note', { path: '../secret.md' }),
    call(3, 'read_note', { path: secret }),
    call(4, 'read_note', { path: 'wiki/../../secret.md' }),
    call(5, 'read_note', { path: 'wiki/escape.md' }),
    call(6, 'read_note', { path: '.obsidian/app.json' }),
    call(7, 'save_note', { title: 'Leak', body: 'x', path: 'wiki/out/leak.md' }),
    call(8, 'save_note', { title: 'Leak', body: 'x', path: '.obsidian/leak.md' }),
    call(9, 'save_note', { title: 'Theirs', body: 'x', path: 'projects/tide/theirs.md' }),
    call(10, 'read_note', {}),
    call(11, 'read_note', { path: 'wiki/tide.md', depth: 2 }),
    call(12, 'save_decision', { title: 't', decision: 'd', rationale: 'r', confidence: 2 }),
  );
  expect(replies.slice(1).map(refusal)).toEqual([
    'vault path ../secret.md is outside the vault',
    `vault path ${secret} is outside the vault`,
    'vault path wiki/../../secret.md is outside the vault',
    'vault path wiki/escape.md is outside the vault',
    'vault path .obsidian/app.json is a vault internal',
    'vault path wiki/out/leak.md is outside the vault',
    'vault path .obsidian/leak.md is a vault internal',
    "projects/tide/theirs.md is in project tide's folder, not lantern-cove's",
    'read_note: path: Invalid input: expected string, received undefined',
    'read_note: arguments: Unrecognized key: "depth"',
    'save_decision: confidence: Too big: expected number to be <=1',
  ]);
  expect(readdirSync(join(cli.home, 'elsewhere'))).toEqual([]);
  expect(existsSync(join(vault, '.obsidian/leak.md'))).toBe(false);
  expect((await mesa('receipts', '--json')).json.data).toEqual([]);
});

test('a General session searches the whole vault and has no project to save a decision for', async () => {
  cli.withTmux();
  await cli.withProject();
  const id = (await mesa('open', '--general', '--json')).json.data.id;
  cli.env = { MESA_SESSION_ID: id, MESA_PROFILE: 'default' };
  put('projects/lantern-cove.md', 'The harbour lights.\n');
  put('wiki/elsewhere.md', '---\nproject: tide\n---\nHarbour lights on another coast.\n');
  const { replies, stderr } = await serve(
    [],
    initialize(),
    call(2, 'search_vault', { query: 'harbour lights' }),
    call(3, 'save_decision', { title: 't', decision: 'd', rationale: 'r' }),
    call(4, 'save_note', { title: 'Coast notes', body: 'Two coasts.' }),
  );
  expect(stderr).toBe(`mesa-vault: serving session ${id} (General)\n`);
  expect(
    answer(replies[1])
      .items.map((i: { path: string }) => i.path)
      .sort(),
  ).toEqual(['projects/lantern-cove.md', 'wiki/elsewhere.md']);
  expect(refusal(replies[2])).toBe('a General session has no project to save it for');
  expect(answer(replies[3])).toMatchObject({ path: 'wiki/notes/coast-notes.md', changed: true });
});

test('vault mcp --tools prints the fixed tool definitions, one line each, without serving', async () => {
  const out = await mesa('vault', 'mcp', '--tools', '--json');
  expect(out.serve).toBeUndefined();
  const { tools } = out.json.data;
  expect(tools.map((t: { name: string }) => t.name)).toEqual(TOOLS);
  for (const t of tools) {
    expect(t.description).toMatch(/^[^\n]{1,100}$/);
    expect(t.inputSchema).toMatchObject({ type: 'object', additionalProperties: false });
    expect(t.inputSchema).not.toHaveProperty('$schema');
  }
  // What every provider pays for in context: ADR-0011 records this size, so change both together.
  expect(Buffer.byteLength(JSON.stringify({ tools }))).toBe(2608);
  const text = (await mesa('vault', 'mcp', '--tools')).stdout.split('\n');
  expect(text.map((line) => line.split(' ')[0])).toEqual([...TOOLS, '']);
  expect(text[0]).toMatch(/^project_context {2}Project overview: hub, index, notes/);
});
