import { sessionLabel } from '../display.js';
import { clip } from '../lib/clip.js';
import type { RegistryEntry } from '../projects/registry.js';
import { projectLabel } from '../sessions/general.js';
import { isSessionId } from '../sessions/id.js';
import type { SessionRecord } from '../sessions/record.js';
import { sessionUri } from '../sessions/uri.js';
import type { CanvasData, CanvasNode } from '../vault/canvas.js';
import type { VaultItem } from '../vault/item.js';
import { sessionSummaryPath } from '../vault/layout.js';

export const MAP_WARNING = 'Generated by Mesa. Update map replaces personal edits to this file.';
const groupId = (project: string) => `project:${encodeURIComponent(project)}`;
const sessionId = (s: SessionRecord) => `session:${encodeURIComponent(s.project)}:${s.id}`;

/** A deterministic saved-session map; selection time/profile are supplied by the caller. */
export function buildMap(
  records: SessionRecord[],
  projects: RegistryEntry[],
  items: VaultItem[],
  options: { profile: string; from: number; through: number; all?: boolean },
): CanvasData {
  const byId = new Map(records.map((r) => [r.id, r]));
  const selected = new Set<string>();
  for (const record of records) {
    const started = Date.parse(record.startedAt);
    if (!options.all && (started < options.from || started > options.through)) continue;
    let ancestor: SessionRecord | undefined = record;
    while (ancestor && !selected.has(ancestor.id)) {
      selected.add(ancestor.id);
      ancestor = ancestor.resumedFrom ? byId.get(ancestor.resumedFrom) : undefined;
    }
  }
  const included = records.filter((r) => selected.has(r.id));
  const names = [...new Set(included.map((r) => r.project))].sort();
  const nodes: CanvasNode[] = [
    { id: 'mesa:warning', type: 'text', x: 0, y: -140, width: 940, height: 100, text: MAP_WARNING },
  ];
  let y = 0;
  for (const project of names) {
    const sessions = included
      .filter((r) => r.project === project)
      .sort(
        (a, b) => Date.parse(a.startedAt) - Date.parse(b.startedAt) || a.id.localeCompare(b.id),
      );
    const height = Math.ceil(sessions.length / 3) * 240 + 80;
    nodes.push({
      id: groupId(project),
      type: 'group',
      x: 0,
      y,
      width: 1060,
      height,
      label: projects.find((p) => p.name === project)?.label || projectLabel(project),
    });
    sessions.forEach((s, i) => {
      const geometry = {
        id: sessionId(s),
        x: 20 + (i % 3) * 340,
        y: y + 60 + Math.floor(i / 3) * 240,
        width: 320,
        height: 210,
      };
      const summary = sessionSummaryPath(s.id);
      if (
        items.some((item) => item.path === summary && item.kind === 'markdown' && !item.unavailable)
      ) {
        nodes.push({ ...geometry, type: 'file', file: summary });
      } else {
        const url = sessionUri(s.id, options.profile);
        nodes.push({
          ...geometry,
          type: 'text',
          text: `${sessionLabel(s)}\n${s.agent}: ${s.lastState.state}\n${clip(s.goal ?? '', 200)}\n[Open in Mesa](${url})`,
        });
      }
    });
    y += height + 80;
  }
  const edges = [...included]
    .sort((a, b) => a.id.localeCompare(b.id))
    .flatMap((r) => {
      const predecessor = r.resumedFrom ? byId.get(r.resumedFrom) : undefined;
      return predecessor && selected.has(predecessor.id)
        ? [
            {
              id: `resume:${predecessor.id}:${r.id}`,
              fromNode: sessionId(predecessor),
              toNode: sessionId(r),
            },
          ]
        : [];
    });
  return { nodes, edges };
}

/** Interpret Mesa's stable session namespace once for both saved-map callers. */
export function mapSession(node: CanvasNode): {
  project: string;
  id: string;
  label: string;
  summary?: string;
} | null {
  if (!node.id.startsWith('session:') || (node.type !== 'file' && node.type !== 'text'))
    return null;
  const [project, id, extra] = node.id.slice('session:'.length).split(':');
  if (project === undefined || !id || extra !== undefined || !isSessionId(id)) return null;
  try {
    return {
      project: decodeURIComponent(project),
      id,
      label: node.type === 'text' ? node.text.split('\n')[0] || id : id,
      ...(node.type === 'file' ? { summary: node.file } : {}),
    };
  } catch {
    return null;
  }
}

export type MapGroup = {
  project: string;
  label: string;
  sessions: { id: string; label: string; summary?: string }[];
};
/** Interpret Mesa's stable node namespaces once; the UI never reconstructs the graph from Board rows. */
export function mapGroups(canvas: CanvasData): MapGroup[] {
  return canvas.nodes.flatMap((group) => {
    if (group.type !== 'group' || !group.id.startsWith('project:')) return [];
    let project: string;
    try {
      project = decodeURIComponent(group.id.slice('project:'.length));
    } catch {
      return [];
    }
    const sessions = canvas.nodes.flatMap((node) => {
      const session = mapSession(node);
      if (!session || session.project !== project) return [];
      const { project: _, ...target } = session;
      return [target];
    });
    return [{ project, label: group.label || projectLabel(project), sessions }];
  });
}
