import { appendFileSync } from 'node:fs';
import { expect, test } from 'vitest';
import { codexWorld, plantTranscript, tempDir } from '../../testing/index.js';
import { nativePrompt } from './native-prompt.js';

const ID = '5b1e2f40-9c3d-4e7a-8f10-2a3b4c5d6e7f';
const THREAD = '01a0e14e-be41-72f1-a81b-e25d2198602a';

const user = (content: unknown, extra: object = {}) => ({
  type: 'user',
  ...extra,
  message: { role: 'user', content },
});

/** The first prompt of a Claude Code transcript of `entries`. */
function claudePrompt(...entries: object[]) {
  const home = tempDir();
  const cwd = `${home}/src/lantern-cove`;
  plantTranscript(home, ID, cwd, entries.map((l) => JSON.stringify(l)).join('\n'));
  return nativePrompt({ home, env: {} }, { agent: 'claude', id: ID });
}

test("a Claude Code conversation's first prompt skips commands, caveats, meta lines and tool results", () => {
  const found = claudePrompt(
    { type: 'summary' },
    user('Caveat: the messages below were generated by the user while running local commands.', {
      isMeta: true,
    }),
    user('<command-name>/clear</command-name>'),
    user([{ type: 'tool_result', content: 'ok' }]),
    user([{ type: 'text', text: '  Fix the\n flaky   tide pump test  ' }]),
    user('Second prompt'),
  );
  expect(found.prompt).toBe('Fix the flaky tide pump test');
  expect(found.updatedAt).toMatch(/^\d{4}-\d\d-\d\dT/);
});

test('a long first prompt is clipped to one line of 60 characters', () => {
  const prompt = claudePrompt(user(`Chart ${'the harbor tides '.repeat(10)}`)).prompt ?? '';
  expect(prompt.length).toBeLessThanOrEqual(60);
  expect(prompt.endsWith('...')).toBe(true);
});

test('a conversation with no prompt, or none on disk, has none', () => {
  expect(claudePrompt(user('<local-command-stdout>ok</local-command-stdout>')).prompt).toBe(
    undefined,
  );
  expect(nativePrompt({ home: tempDir(), env: {} }, { agent: 'claude', id: ID })).toEqual({});
});

test("a Codex thread's first prompt skips the context and instructions Codex injects", () => {
  const codex = codexWorld();
  const file = codex.rollout({
    id: THREAD,
    cwd: '/src/tide-pool',
    startedAt: '2026-09-24T11:50:00.000Z',
  });
  const said = (text: string) =>
    JSON.stringify({
      type: 'response_item',
      payload: { type: 'message', role: 'user', content: [{ type: 'input_text', text }] },
    });
  appendFileSync(
    file,
    `\n${[
      said('# AGENTS.md instructions for /src/tide-pool'),
      said('<environment_context>cwd</environment_context>'),
      said('Wire the lantern relay'),
    ].join('\n')}\n`,
  );
  const deps = { home: tempDir(), env: codex.env };
  expect(nativePrompt(deps, { agent: 'codex', id: THREAD }).prompt).toBe('Wire the lantern relay');
  expect(nativePrompt(deps, { agent: 'antigravity', id: THREAD })).toEqual({});
});
