import type { ReceiptInput } from './schema.js';

// One example per receipt type. The golden files in golden/ are these, written by writeReceipt;
// docs/receipts.md shows the same files (a test keeps them in step).
export const EXAMPLES: Record<ReceiptInput['type'], ReceiptInput> = {
  action: {
    type: 'action',
    profile: 'default',
    project: 'lantern-cove',
    status: 'ok',
    command: 'mesa register lantern-cove --create',
    inputs: { dir: '/src/lantern-cove', create: true },
    outputs: { path: '/src/lantern-cove', wroteMesaYaml: true },
    summary: 'Registered project lantern-cove',
  },
  session: {
    type: 'session',
    profile: 'default',
    project: 'lantern-cove',
    session: 'a1b2c3',
    agent: 'claude',
    started: '2026-09-24T09:30',
    ended: '2026-09-24T11:05',
    status: 'ok',
    command: 'mesa open lantern-cove',
    outputs: {
      events: { send: 14, exited: 1 },
      lastState: {
        state: 'done',
        confidence: 0.85,
        at: '2026-09-24T11:05:00.000Z',
        source: 'tmux-hook',
      },
    },
    summary: 'Session a1b2c3 on lantern-cove ended done after 1 h 35 min',
    details: 'Resumed once. Last output: "All tests pass."',
  },
  skill: {
    type: 'skill',
    profile: 'default',
    project: 'lantern-cove',
    session: 'a1b2c3d4',
    agent: 'claude',
    ended: '2026-09-24T12:01',
    status: 'failed',
    command: 'mesa run tidy-readme --project lantern-cove',
    inputs: { skill: 'tidy-readme', args: [] },
    outputs: {
      agentSessionId: '00000000-0000-4000-8000-000000000001',
      durationMs: 60000,
      output: '~/.mesa/default/sessions/runs/a1b2c3d4.json',
      reason: 'claude exited with status 1',
      events: { exited: 1 },
      lastState: { state: 'failed', confidence: 1, at: '2026-09-24T12:01:00.000Z', source: 'mesa' },
    },
    cost: 0.042,
    summary: 'Skill tidy-readme failed on lantern-cove',
  },
  decision: {
    type: 'decision',
    profile: 'default',
    status: 'ok',
    command: 'mesa decide',
    decisions: [
      {
        question: 'Allow sending this prompt?',
        kind: 'Choice',
        answer: 'block',
        probabilities: { allow: 0.08, ask: 0.22, block: 0.7 },
        confidence: 0.81,
        backend: 'rules',
      },
      {
        question: 'Is the prompt destructive?',
        kind: 'Noul',
        answer: true,
        probabilities: 0.93,
        backend: 'rules',
      },
    ],
    inputs: { state: { prompt: 'git push --force' } },
    outputs: { latencyMs: 0 },
    summary: 'Faro answered 2 questions (rules)',
  },
};
